### PR TITLE
adding python docs

### PR DESCRIPTION
**Pull request by VenkateswaranJ**
Age 28. lol :)

### CODE REVIEW

**Comment by murugadaas** [comment]
> 
> 
> Age 28. lol :)

vayasu = 28; till havig 20 yrs more

**Comment by murugadaas** [comment]
https://www.coursera.org/specializations/java-programming
7 days trail
gonna try this in sometime

**Comment by VenkateswaranJ** [comment]
Yeah you can learn, but they won't give certificate for free. I think it comes around 2500.rs

**Comment by murugadaas** [comment]
> 
> 
> Yeah you can learn, but they won't give certificate for free. I think it comes around 2500.rs

certificatela aprom pathukalam,mudinja alvuvku antha 7 naala ethathu suck panidanum

**Pull request merged**
